### ISSUE TITLE
Add heap sort in the sorting folder

### ISSUE THREAD

**Issue by SanyamAgrawal07** [GDSC-CEC/HacktoberFest-2022-Cpp#102]
Heap sort, an important algorithm is absent in the sorting folder

Please assign me this issue under hacktoberfest

**Comment by ShaileshKumar007** [comment]
> Heap sort, an important algorithm is absent in the sorting folder
> 
> Please assign me this issue under hacktoberfest

Great. I'm assigning this issue to you. Kindly make sure to close this issue through your PR

**Comment by SanyamAgrawal07** [comment]
Thanks, and sure!

**Comment by ShaileshKumar007** [comment]
@SanyamAgrawal07 Also make sure to add the README file along with your solution. Just follow the folder structure that is there in the repo

**Comment by SanyamAgrawal07** [comment]
@ShaileshKumar007 Please review my PR #102

**Comment by ShaileshKumar007** [comment]
Your PR has been merged. Therefore I'm closing this issue
